<script>
    import LineChart from '$lib/viz/LineChart.svelte'
    import AreaChart from '$lib/viz/AreaChart.svelte'
    import BubbleChart from '$lib/viz/BubbleChart.svelte'
    import BarChart from '$lib/viz/BarChart.svelte'
    import Histogram from '$lib/viz/Histogram.svelte'
    import ScatterPlot from '$lib/viz/ScatterPlot.svelte'
    import DataTable from '$lib/viz/DataTable.svelte'
    import Value from '$lib/viz/Value.svelte'

    import testData from '/src/data/test.json'
    import pctTest from '/src/data/pct_test.json'
    import countries from '/src/data/countries.json'
    import test_string from '/src/data/test_string.json'
    import test_dates from '/src/data/test_dates.json'
    import test_dates_stacked from '/src/data/test_dates_stacked.json'
    import test_weeks from '/src/data/test_weeks.json'
    import test_months from '/src/data/test_months.json'
    import test_quarters from '/src/data/test_quarters.json'
    import test_years from '/src/data/test_years.json'

    let data = {}

    let testH = [
        {a:5},
        {a:5},
        {a:9},
        {a:9},
        {a:7},
        {a:8},
        {a:6},
        {a:6}
    ]

    let textP = [
        {dept: 'Public Works', category: 'Pothole Repair', complaints: 24105},
{dept: 'Public Works', category: 'Debris in Street', complaints: 16378},
{dept: 'Public Works', category: 'Tree Issue ROW', complaints: 14871},
{dept: 'Public Works', category: 'Obstruction in ROW', complaints: 10528},
{dept: 'Public Works', category: 'Sidewalk Repair', complaints: 9206},
{dept: 'Public Works', category: 'Pavement Failure', complaints: 6941},
{dept: 'Public Works', category: 'Tree Issue ROW/Emergency (PW)', complaints: 5675},
{dept: 'Public Works', category: 'Tree Issue ROW/Maintenance (PW)', complaints: 4688},
{dept: 'Public Works', category: 'Alley & Unpaved Street Maintenance', complaints: 3160},
{dept: 'Public Works', category: 'Mowing Medians', complaints: 2743},
{dept: 'Public Works', category: 'Curb/Gutter Repair', complaints: 1435},
{dept: 'Public Works', category: 'Sidewalk/Curb Ramp/Route - NEW', complaints: 1272},
{dept: 'Public Works', category: 'Street Resurfacing', complaints: 1029},
{dept: 'Public Works', category: 'School Zone - New/Review/Changes', complaints: 696},
{dept: 'Public Works', category: 'Street Resurfacing Inquiry', complaints: 611},
{dept: 'Public Works', category: 'Guardrail New/Repair', complaints: 402},
{dept: 'Public Works', category: 'Guardrail Repair', complaints: 357},
{dept: 'Public Works', category: 'Roadway Spillage', complaints: 323},
{dept: 'Public Works', category: 'Bridge Repair', complaints: 294},
{dept: 'Public Works', category: 'Barricade Request', complaints: 228},
{dept: 'Public Works', category: 'School Issues - Crossing Guards', complaints: 171},
{dept: 'Public Works', category: 'Bicycle Issues', complaints: 97},
{dept: 'Public Works', category: 'Road Sanding Request', complaints: 59},
{dept: 'Public Works', category: 'Fence/Wall Repair', complaints: 42},
{dept: 'Public Works', category: 'Tree Issue ROW/Maintenance (PARD)', complaints: 29},
{dept: 'Public Works', category: 'Guardrail - New', complaints: 27},
{dept: 'Public Works', category: 'Tree Issue ROW/Emergency (PARD)', complaints: 24},
{dept: 'Public Works', category: 'Fence Repair - MOPAC', complaints: 10}
    ]
    

    let binCheck = 
    [
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 7},
    {a: 8}
]
let bc3 = [
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},

    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},

    {a: 2},


    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},



    {a: 4},
    {a: 5},
    {a: 6},
    {a: 7}
]



let binCheck2 = 
    [
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 1},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 2},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 3},
    {a: 7},
    {a: 8}
]

let binNull = 
    [
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: null},
    {a: 5},
    {a: 5},
    {a: 5},
    {a: 5},
    {a: 5},
    {a: 5},
    {a: 5},
    {a: 2}
]

let singleVal = [
    {a: 1},
]
 </script>

<LineChart data={testData} x=x y=y markers=false/>
<LineChart data={testData} x=x y=y markers=true/>
<LineChart data={testData} x=x y=y markers=true markerShape=emptyCircle/>
