/**
 * Documentation module for the CLI.
 * Docs content is pre-bundled via scripts/bundle-docs.ts.
 * Component schemas are loaded via Vite glob from @evidence/core.
 */

import { gunzipSync } from 'node:zlib';
import type { UserComponentSchema } from '@evidence/core/user-components/types';
import { docsBundleGzBase64 } from './docs-bundle.generated';

// Pre-bundled docs content (generated by scripts/bundle-docs.ts)
const allDocs = JSON.parse(
	gunzipSync(Buffer.from(docsBundleGzBase64, 'base64')).toString('utf-8')
) as Record<string, string>;

// Component schemas loaded via Vite (works because @evidence/core is aliased within the project)
const componentSchemas = import.meta.glob('@evidence/core/user-components/tags/**/schema.ts', {
	eager: true,
	import: 'schema'
}) as Record<string, UserComponentSchema>;

// ============================================================================
// Types
// ============================================================================

export interface ComponentInfo {
	name: string;
	category: string;
}

export interface DocEntry {
	path: string;
	title: string;
	description: string;
	category: string;
	content: string;
}

export interface SearchResult {
	path: string;
	title: string;
	description: string;
	category: string;
	snippet: string;
	score: number;
}

// ============================================================================
// Component helpers
// ============================================================================

function buildComponentList(): ComponentInfo[] {
	const components: ComponentInfo[] = [];

	for (const [_path, schema] of Object.entries(componentSchemas)) {
		if (schema.render) {
			components.push({
				name: schema.render,
				category: (schema as { category?: string }).category ?? 'other'
			});
		}
	}

	return components.sort(
		(a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name)
	);
}

export const componentList = buildComponentList();

// ============================================================================
// Search index
// ============================================================================

function parseFrontmatter(content: string): { title: string; description: string } {
	const match = content.match(/^---\n([\s\S]*?)\n---/);
	if (!match) return { title: '', description: '' };

	const yaml = match[1];
	const titleMatch = yaml.match(/title:\s*['"]?([^'"\n]+)['"]?/);
	const descMatch = yaml.match(/description:\s*['"]?([^'"\n]+)['"]?/);

	return {
		title: titleMatch?.[1]?.trim() ?? '',
		description: descMatch?.[1]?.trim() ?? ''
	};
}

function getCategoryFromPath(path: string): string {
	if (path.includes('/components/')) return 'Components';
	if (path.includes('/core-concepts/')) return 'Core Concepts';
	if (path.includes('/features/')) return 'Features';
	if (path.includes('/data-sources/')) return 'Data Sources';
	return 'Guides';
}

function buildSearchIndex(): DocEntry[] {
	return Object.entries(allDocs).map(([path, content]) => {
		const { title, description } = parseFrontmatter(content);
		const category = getCategoryFromPath(path);
		return {
			path,
			title,
			description,
			category,
			content
		};
	});
}

export const searchIndex = buildSearchIndex();

// ============================================================================
// Search
// ============================================================================

function extractSnippet(content: string, query: string, maxLength: number = 150): string {
	const lowerContent = content.toLowerCase();
	const lowerQuery = query.toLowerCase();
	const index = lowerContent.indexOf(lowerQuery);

	if (index === -1) return '';

	const start = Math.max(0, index - 50);
	const end = Math.min(content.length, index + query.length + maxLength - 50);

	let snippet = content.slice(start, end);
	if (start > 0) snippet = '...' + snippet;
	if (end < content.length) snippet = snippet + '...';

	return snippet.replace(/\n+/g, ' ').trim();
}

export function searchDocs(query: string, limit: number = 10): SearchResult[] {
	const lowerQuery = query.toLowerCase();
	const terms = lowerQuery.split(/\s+/).filter((t) => t.length > 0);

	const results: SearchResult[] = [];

	for (const doc of searchIndex) {
		let score = 0;
		const lowerTitle = doc.title.toLowerCase();
		const lowerDesc = doc.description.toLowerCase();
		const lowerContent = doc.content.toLowerCase();

		for (const term of terms) {
			if (lowerTitle === term) score += 100;
			else if (lowerTitle.includes(term)) score += 50;

			if (lowerDesc.includes(term)) score += 20;
			if (lowerContent.includes(term)) score += 5;
		}

		if (score > 0) {
			const snippet =
				extractSnippet(doc.content, query) ||
				extractSnippet(doc.content, terms[0]) ||
				doc.description;

			results.push({
				path: doc.path,
				title: doc.title,
				description: doc.description,
				category: doc.category,
				snippet,
				score
			});
		}
	}

	return results.sort((a, b) => b.score - a.score).slice(0, limit);
}

export function readDoc(path: string): DocEntry | undefined {
	return searchIndex.find((d) => d.path === path || d.path === path.replace(/^\//, ''));
}

// ============================================================================
// Component schema helpers
// ============================================================================

export function getSchemaByName(name: string): UserComponentSchema | undefined {
	for (const [_path, schema] of Object.entries(componentSchemas)) {
		if (schema.render === name) {
			return schema;
		}
	}
	return undefined;
}

export function getAttributeType(attr: UserComponentSchema['attributes'][string]): string {
	if (attr.type === String) return 'string';
	if (attr.type === Number) return 'number';
	if (attr.type === Boolean) return 'boolean';
	if (attr.type === Array) return 'array';
	if (typeof attr.type === 'object' && 'schema' in attr.type) return 'options group';
	return 'unknown';
}

export function getComponentCategory(componentName: string): string {
	const found = componentList.find((c) => c.name === componentName);
	return found?.category ?? 'other';
}

export function listAllComponentNames(): string[] {
	return Object.values(componentSchemas)
		.map((s) => s.render)
		.sort();
}

export function getComponentDetail(name: string) {
	const schema = getSchemaByName(name);
	if (!schema) return null;

	const category = getComponentCategory(name);
	const attrEntries = Object.entries(schema.attributes);

	const attributes: Record<string, object> = {};
	for (const [attrName, attr] of attrEntries) {
		// `matches` is the enum/allowed-value list for an attribute (e.g.
		// ['default','well','card']); surface it so machine consumers can see the
		// valid values for enum/format-code attributes.
		const allowedValues = Array.isArray(attr.matches) ? attr.matches : undefined;
		attributes[attrName] = {
			type: getAttributeType(attr),
			required: attr.required ?? false,
			default: attr.default,
			description: attr.description,
			...(allowedValues ? { allowedValues } : {})
		};
	}

	return {
		name: schema.render,
		category,
		description: schema.description,
		selfClosing: schema.selfClosing,
		example:
			schema.examples?.find((e) => e.hero)?.example?.trim() ??
			schema.examples?.[0]?.example?.trim(),
		attributes,
		examples:
			schema.examples?.map((e) => ({
				title: e.title,
				code: e.example.trim()
			})) ?? []
	};
}
