export const SIDEBAR_COOKIE_NAME = 'sidebar:state';
export const SIDEBAR_WIDTH_COOKIE_NAME = 'sidebar:width';
export const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;
export const SIDEBAR_WIDTH_MOBILE = '18rem';
export const SIDEBAR_WIDTH_ICON = '3rem';
export const SIDEBAR_WIDTH_DEFAULT_PX = 256;
export const SIDEBAR_WIDTH_MIN_PX = 240;
export const SIDEBAR_WIDTH_MAX_PX = 720;
export const SIDEBAR_KEYBOARD_SHORTCUT = 'b';
