FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders UNION ALL
FROM orders UNION ALL FROM orders