import type { Component } from 'svelte';
import {
	TrendingUp,
	TrendingDown,
	Clock,
	Calendar,
	CheckCircle,
	XCircle,
	Info,
	AlertCircle,
	HelpCircle,
	Eye,
	EyeOff,
	User,
	Users,
	SlidersVertical,
	Cog,
	Calculator,
	Plus,
	Minus,
	ArrowUpCircle,
	ArrowDownCircle,
	ArrowRightCircle,
	ArrowLeftCircle,
	Star,
	Heart,
	Search,
	File,
	FileText,
	Home,
	Mail,
	Filter,
	Share,
	Bell,
	Trash,
	CreditCard,
	Globe,
	Key,
	Croissant,
	Map,
	RotateCw,
	Rewind,
	Landmark,
	ReceiptText,
	Activity,
	ChartColumn,
	ChartPie,
	ChartNoAxesCombined,
	Goal,
	Rocket,
	Trophy,
	Apple,
	Cookie,
	Donut,
	Beef,
	Cake,
	Soup,
	Utensils,
	Milk,
	Nut,
	Pyramid,
	Triangle,
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	ChevronsDown,
	ChevronsLeft,
	ChevronsRight,
	ChevronsUp,
	Menu,
	ExternalLink,
	Edit,
	Trash2,
	Copy,
	Save,
	Download,
	Upload,
	Send,
	RefreshCw,
	Redo,
	Undo,
	Folder,
	FolderOpen,
	Image,
	FileImage,
	UserPlus,
	UserMinus,
	UserCheck,
	Lock,
	Unlock,
	LogIn,
	LogOut,
	MessageSquare,
	MessageCircle,
	Phone,
	PhoneCall,
	BellOff,
	Video,
	VideoOff,
	Play,
	Pause,
	Square,
	SkipBack,
	SkipForward,
	Volume,
	Volume1,
	Volume2,
	VolumeOff,
	VolumeX,
	Bookmark,
	Tag,
	Link,
	Unlink,
	Share2,
	AlertTriangle,
	Loader,
	MoreVertical,
	MoreHorizontal,
	Grid,
	List,
	Maximize,
	Minimize,
	ZoomIn,
	ZoomOut,
	ThumbsUp,
	ThumbsDown,
	ShoppingCart,
	DollarSign,
	Camera,
	Printer,
	Monitor,
	Smartphone,
	Laptop,
	CloudSunRain,
	SunSnow,
	ThermometerSun,
	ThermometerSnowflake,
	Cloudy,
	CloudRainWind,
	CloudRain,
	Wind,
	Sun,
	CloudSnow,
	Thermometer,
	CloudDrizzle,
	CloudSun,
	Cloud,
	CloudLightning,
	Snowflake,
	Flame,
	Atom,
	Fuel,
	Magnet,
	Factory,
	TreeDeciduous,
	Waypoints,
	Plug,
	Dam,
	Battery
} from 'lucide-svelte';
import { logger } from '../../shims/logger';

// Map of icon names to components
const iconMap = {
	'trending-up': TrendingUp,
	'trending-down': TrendingDown,
	clock: Clock,
	calendar: Calendar,
	check: CheckCircle,
	x: XCircle,
	info: Info,
	'alert-circle': AlertCircle,
	'help-circle': HelpCircle,
	eye: Eye,
	'eye-off': EyeOff,
	user: User,
	users: Users,
	settings: SlidersVertical,
	cog: Cog,
	plus: Plus,
	minus: Minus,
	up: ArrowUpCircle,
	down: ArrowDownCircle,
	right: ArrowRightCircle,
	left: ArrowLeftCircle,
	star: Star,
	heart: Heart,
	search: Search,
	file: File,
	'file-text': FileText,
	home: Home,
	mail: Mail,
	filter: Filter,
	share: Share,
	bell: Bell,
	trash: Trash,
	'credit-card': CreditCard,
	globe: Globe,
	key: Key,
	croissant: Croissant,
	map: Map,
	rotate: RotateCw,
	rewind: Rewind,
	bank: Landmark,
	receipt: ReceiptText,
	activity: Activity,
	'chart-column': ChartColumn,
	'chart-pie': ChartPie,
	'chart-no-axes-combined': ChartNoAxesCombined,
	goal: Goal,
	rocket: Rocket,
	trophy: Trophy,
	apple: Apple,
	cookie: Cookie,
	donut: Donut,
	beef: Beef,
	cake: Cake,
	soup: Soup,
	utensils: Utensils,
	milk: Milk,
	nut: Nut,
	pyramid: Pyramid,
	triangle: Triangle,
	'arrow-down': ArrowDown,
	'arrow-left': ArrowLeft,
	'arrow-right': ArrowRight,
	'arrow-up': ArrowUp,
	'chevron-down': ChevronDown,
	'chevron-left': ChevronLeft,
	'chevron-right': ChevronRight,
	'chevron-up': ChevronUp,
	'chevrons-down': ChevronsDown,
	'chevrons-left': ChevronsLeft,
	'chevrons-right': ChevronsRight,
	'chevrons-up': ChevronsUp,
	menu: Menu,
	'external-link': ExternalLink,
	'check-circle': CheckCircle,
	'x-circle': XCircle,
	edit: Edit,
	'trash-2': Trash2,
	copy: Copy,
	save: Save,
	download: Download,
	upload: Upload,
	send: Send,
	refresh: RefreshCw,
	redo: Redo,
	undo: Undo,
	folder: Folder,
	'folder-open': FolderOpen,
	image: Image,
	'file-image': FileImage,
	'user-plus': UserPlus,
	'user-minus': UserMinus,
	'user-check': UserCheck,
	lock: Lock,
	unlock: Unlock,
	'log-in': LogIn,
	'log-out': LogOut,
	'message-square': MessageSquare,
	'message-circle': MessageCircle,
	phone: Phone,
	'phone-call': PhoneCall,
	'bell-off': BellOff,
	video: Video,
	'video-off': VideoOff,
	play: Play,
	pause: Pause,
	stop: Square,
	'skip-back': SkipBack,
	'skip-forward': SkipForward,
	volume: Volume,
	'volume-1': Volume1,
	'volume-2': Volume2,
	'volume-off': VolumeOff,
	'volume-x': VolumeX,
	bookmark: Bookmark,
	tag: Tag,
	link: Link,
	unlink: Unlink,
	'share-2': Share2,
	'alert-triangle': AlertTriangle,
	loader: Loader,
	'more-vertical': MoreVertical,
	'more-horizontal': MoreHorizontal,
	grid: Grid,
	list: List,
	maximize: Maximize,
	minimize: Minimize,
	'zoom-in': ZoomIn,
	'zoom-out': ZoomOut,
	'thumbs-up': ThumbsUp,
	'thumbs-down': ThumbsDown,
	'shopping-cart': ShoppingCart,
	'dollar-sign': DollarSign,
	camera: Camera,
	printer: Printer,
	monitor: Monitor,
	smartphone: Smartphone,
	laptop: Laptop,
	calculator: Calculator,
	'cloud-sun-rain': CloudSunRain,
	'sun-snow': SunSnow,
	'thermometer-sun': ThermometerSun,
	'thermometer-snowflake': ThermometerSnowflake,
	cloudy: Cloudy,
	'cloud-rain-wind': CloudRainWind,
	'cloud-rain': CloudRain,
	wind: Wind,
	sun: Sun,
	'cloud-snow': CloudSnow,
	thermometer: Thermometer,
	'cloud-drizzle': CloudDrizzle,
	'cloud-sun': CloudSun,
	cloud: Cloud,
	'cloud-lightning': CloudLightning,
	snowflake: Snowflake,
	flame: Flame,
	atom: Atom,
	fuel: Fuel,
	magnet: Magnet,
	factory: Factory,
	'tree-deciduous': TreeDeciduous,
	waypoints: Waypoints,
	plug: Plug,
	dam: Dam,
	battery: Battery
};

// Icon names for auto complete are now defined in icon-names.ts

/**
 * Gets a Lucide icon by name from the curated set of common icons
 * @param iconName - The name of the icon (e.g., 'calendar', 'user', 'settings')
 * @returns The Svelte component for the icon, or null if not found
 */
export function loadLucideIcon(iconName: string): Component | null {
	if (!iconName) return null;

	// Normalize the icon name to lowercase with dashes
	const normalizedName = iconName.toLowerCase().replace(/[_\s]/g, '-');

	const IconComponent = iconMap[normalizedName as keyof typeof iconMap];

	if (IconComponent) {
		return IconComponent as unknown as Component;
	}

	logger.warn({ iconName, availableIcons: Object.keys(iconMap).join(', ') }, 'Icon not found');
	return null;
}
