/**
 * Pre-build script: bundles docs/ MDX files into a JSON file
 * that the CLI can import without import.meta.glob across project boundaries.
 *
 * Run: bun run scripts/bundle-docs.ts
 */

import { readdir, readFile, writeFile, mkdir } from 'fs/promises';
import { join, relative, parse as parsePath } from 'path';
import { gzipSync } from 'zlib';

const DOCS_DIR = join(import.meta.dir, '../../docs');
const OUTPUT_FILE = join(import.meta.dir, '../src/lib/docs/docs-bundle.generated.ts');

interface DocEntry {
	path: string;
	content: string;
}

async function discoverMdxFiles(dir: string): Promise<DocEntry[]> {
	const entries: DocEntry[] = [];

	async function walk(currentDir: string) {
		const items = await readdir(currentDir, { withFileTypes: true });
		for (const item of items) {
			const fullPath = join(currentDir, item.name);
			if (item.isDirectory()) {
				if (item.name.startsWith('.') || item.name === 'node_modules') continue;
				await walk(fullPath);
			} else if (item.isFile() && item.name.endsWith('.mdx')) {
				const content = await readFile(fullPath, 'utf-8');
				const relativePath = relative(DOCS_DIR, fullPath);
				const parsed = parsePath(relativePath);
				const docPath = join(parsed.dir, parsed.name).replace(/\\/g, '/');
				entries.push({ path: docPath, content });
			}
		}
	}

	await walk(dir);
	return entries.sort((a, b) => a.path.localeCompare(b.path));
}

async function main() {
	const docs = await discoverMdxFiles(DOCS_DIR);

	// Write as a simple object: { [path]: content }
	const bundle: Record<string, string> = {};
	for (const doc of docs) {
		bundle[doc.path] = doc.content;
	}

	await mkdir(join(import.meta.dir, '../src/lib/docs'), { recursive: true });
	// Gzip+base64 rather than raw JSON: markdown compresses ~4x in the compiled binary.
	const gzBase64 = gzipSync(JSON.stringify(bundle), { level: 9 }).toString('base64');
	await writeFile(
		OUTPUT_FILE,
		`// Auto-generated by scripts/bundle-docs.ts - DO NOT EDIT\nexport const docsBundleGzBase64 =\n\t'${gzBase64}';\n`,
		'utf-8'
	);

	console.log(`  Bundled ${docs.length} docs into ${relative(process.cwd(), OUTPUT_FILE)}`);
}

main();
