export const QUERIES_CONTEXT_KEY = '__EVIDENCE_CONTEXTUAL_QUERIES';
export const ALL_QUERIES_CONTEXT_KEY = '__EVIDENCE_ALL_QUERIES';
export const ALL_QUERIES_MUTS_CONTEXT_KEY = '__EVIDENCE_ALL_QUERIES_MUTS';
